#!/bin/bash

# load configuration
if [ -f ~/.magicnoterc ]; then
    source ~/.magicnoterc
elif [ -f /usr/local/etc/magicnoterc ]; then
    source /usr/local/etc/magicnoterc
fi

BINTOP=$MAGICTOP/bin
DATATOP=$MAGICTOP/var
ETCTOP=$MAGICTOP/etc

if [ -f $ETCTOP/magicnote_base ]; then
    source $ETCTOP/magicnote_base
fi

function print_usage()
{
    echo "usage:";
    echo "  \_ magicnote addsource source";
    echo "  \_ magicnote list [-p] [tag1 [ tag2 ...]]";
    echo "  \_ magicnote add [-t tagname]";
    echo "  \_ magicnote rm tag@index [tag2@index2 ...]";
    echo "  \_ magicnote edit tag@index [tag2@index2 ...]";
    echo "  \_ magicnote find [-p] tag1 tag2 ...";
    echo "  \_ magicnote run tag@index [tag2@index2 ...]";
    echo "  \_ magicnote revert";
    echo "  \_ magicnote gc";
}

function action_gc()
{
    cd $MAINNOTE_DIR
    dump_unuseful_list | while read unuseful_file
    do
        rm -f $unuseful_file
        echo "delete $unuseful_file"
    done
}

######## main #########

# print help
if [ $# = 0 ]; then
    print_usage
    exit
fi

# commands
if [ $1 = "addsource" ]; then
    shift
    action_addsource $@
elif [ $1 = "ls" ]; then
    pre_check
    shift
    action_list $@
elif [ $1 = "add" ]; then
    pre_check
    shift
    cleanup
    action_add $@
    cleanup
elif [ $1 = "edit" ]; then
    pre_check
    shift
    action_edit $@
elif [ $1 = "rm" ]; then
    pre_check
    shift
    action_rm $@
elif [ $1 = "find" ]; then
    pre_check
    shift
    action_find $@
elif [ $1 = "run" ]; then
    pre_check
    shift
    action_run $@
elif [ $1 = "gc" ]; then
    pre_check
    shift
    action_gc
elif [ $1 = "revert" ]; then
    pre_check
    shift
    revert_index
else
    echo "unknown arg '$1'"
    print_usage
fi
